balance-phoenix0.1
OpenAngelArena/oaa pull request #3318
Opened 2022-03-08 03:46 UTC by warpdragon

oaa levels only. a few nerfs and a buff. basic abilities do more damage to phoenix. supernova damages enemies more and tanks a few more hits.

2022-03-08 06:00 UTC, DarkoniusXNG requested changes
HP costs don't really need a nerf. Phoenix in general doesn't need a nerf. (I am sure Max will correct me if I am wrong) You may think that hp cost nerfs serve as a counter-weight for the ultimate buff but not really.

2022-03-08 08:16 UTC, TheUnholyWrath commented
> HP costs don't really need a nerf. Phoenix in general doesn't need a nerf. (I am sure Max will correct me if I am wrong) You may think that hp cost nerfs serve as a counter-weight for the ultimate buff but not really.

HP costs scale inherently. Nerfing them just makes you not want to level up the ability. I don't think phoenix is strong enough that he deserves to be nerfed

2022-03-08 13:22 UTC, warpdragon commented on game/scripts/npc/abilities/phoenix_supernova.txt
> +        "max_hero_attacks_scepter"                        "7 12 17 20 24" //OAA; Buff: OAA levels increased from 19 21; parallels max_hero_attacks
Okey doke.

2022-03-08 13:22 UTC, warpdragon commented on game/scripts/npc/abilities/phoenix_supernova.txt
> +        "damage_per_sec"                                  "60 120 180 400 650" //OAA; Buff: OAA levels increased from 360 540.
Okey doke.

2022-03-08 13:40 UTC, warpdragon commented
tested. doesn't crash game

2022-03-11 22:59 UTC, warpdragon commented
this pr is all gummed up

2022-03-11 22:59 UTC, closed without merging